[package]
name = "kiban_commons"
description = "Kiban's commons ğŸ’â€â™‚ï¸"
version = "0.0.1"
edition = "2021"

[dependencies]
smallvec = "1.10"
smallbox = "0.8"
derive_more = "0.99"
getset = "0.1"
miette = "5.5"
